// Synthetic protocol fixtures exercise the validator only. They are never native acceptance evidence.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),zlib=require('node:zlib'),{execFileSync}=require('node:child_process')
const gate=require('../scripts/platform-release-gate.cjs'),version='1.1.11',sha=b=>crypto.createHash('sha256').update(b).digest('hex')
const roots=new Set();test.after(()=>{for(const root of roots)fs.rmSync(root,{recursive:true,force:true})})
function crc32(b){let c=0xffffffff;for(const value of b){c^=value;for(let n=0;n<8;n++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function png(color){const header=Buffer.alloc(13);header.writeUInt32BE(160,0);header.writeUInt32BE(120,4);header[8]=8;header[9]=6;const pixels=Buffer.alloc(120*(160*4+1));for(let y=0;y<120;y++)for(let x=0;x<160;x++){const at=y*641+x*4+1;pixels[at]=color;pixels[at+1]=20;pixels[at+2]=40;pixels[at+3]=255}const chunk=(kind,data)=>{const tag=Buffer.from(kind),b=Buffer.alloc(12+data.length);b.writeUInt32BE(data.length);tag.copy(b,4);data.copy(b,8);b.writeUInt32BE(crc32(Buffer.concat([tag,data])),8+data.length);return b};return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',zlib.deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))])}
const images=[png(30),png(160)]
function packageBytes(name,arch){const b=Buffer.alloc(1024);if(/\.(zip|hap)$/.test(name))b.writeUInt32LE(0x04034b50);else if(/\.dmg$/.test(name))b.write('koly',512);else if(/\.deb$/.test(name))b.write('!<arch>\n');else if(/\.tar\.gz$/.test(name)){b[0]=31;b[1]=139}else if(/\.AppImage$/.test(name)){b.write('\x7fELF',0,'binary');b[4]=2;b[5]=1;b.write('AI\x02',8,'binary');b.writeUInt16LE(arch==='arm64'?183:62,18)}else{b.write('MZ');b.writeUInt32LE(64,60);b.write('PE\0\0',64,'binary');b.writeUInt16LE(0x8664,68)}return b}
function names(id){if(id==='windows-x64')return[`KAMUCL-${version}.exe`,`KAMUCL-${version}-windows-x64.zip`,`KAMUCL-${version}-windows-x64-unpacked.zip`];const[p,a]=id.split('-');return(p==='mac'?['dmg','zip']:p==='harmonyos'?['hap']:['AppImage','deb','tar.gz']).map(e=>`KAMUCL-${version}-${p}-${a}.${e}`)}
const rows=ids=>ids.map(name=>({name,status:'passed',expected:true,actual:true})),put=(root,file,b)=>{const target=path.join(root,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,b);return{path:file,sha256:sha(Buffer.from(b)),size:Buffer.byteLength(b)}}
function fixture(scope='desktop'){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'kamucl-gate-unit-'));roots.add(root)
 put(root,'package.json',JSON.stringify({version,devDependencies:{electron:'44.3.0'}}));put(root,`docs/validation-${version}/parity-matrix.json`,JSON.stringify({version,features:[{functions:gate.baselineFunctions}],inventory:{routes:gate.baselineRoutes.map(id=>({id})),ipcChannelCount:280,ipcChannels:gate.baselineChannels.map(channel=>({channel}))}}));put(root,'platforms/harmonyos/runtime.lock.json',JSON.stringify({electronVersion:'37.2.0'}));put(root,'.gitignore','release/\n')
 const git=args=>execFileSync('git',args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']});git(['init','--quiet']);git(['add','.']);git(['-c','user.name=Protocol unit test','-c','user.email=unit@example.invalid','commit','--quiet','-m','Synthetic schema fixture only']);const sourceCommit=git(['rev-parse','HEAD']).trim()
 const report={schema:2,scope,version,sourceCommit,independentReviewer:'independent-unit-assessor',platforms:[]};const bodies=new Map()
 for(const id of scope==='harmonyos'?['harmonyos-arm64']:gate.targets){
  const[platform,architecture]=id.split('-'),runtimeVersion=platform==='harmonyos'?'37.2.0':'44.3.0',artifacts=names(id).map(name=>({name,...put(root,'release/'+name,packageBytes(name,architecture))})).map(({path:ignored,...a})=>a),artifactSHA256=Object.fromEntries(artifacts.map(a=>[a.name,a.sha256]));const entry={id,artifacts,evidence:[]};report.platforms.push(entry)
  function add(kind,suffix='',osVersion=platform==='linux'?'Ubuntu 24.04':platform==='mac'?'macOS 13.7':platform==='windows'?'Windows 11':'HarmonyOS PC 5.0.5'){
   const key=kind+suffix,host={platform,architecture,osVersion,displayFrequency:60},source=kind==='independent-review'?'independent-review':['screenshots','original-video','frame-timings'].includes(kind)?'native-capture':kind==='native-game'?'native-game':'native-product',payload={};const body={schema:1,kind,source,version,sourceCommit,platformId:id,architecture,runtimeVersion,artifactSHA256,host,run:{id:id+'-'+key,source:'native-desktop',command:'synthetic-unit-protocol-not-a-real-native-command',exitCode:0,startedAt:'2026-10-04T01:00:00Z',endedAt:'2026-10-04T01:01:00Z'},payload,attachments:[]}
   const attach=(aid,role,b)=>body.attachments.push({id:aid,role,...put(root,`release/proof/${id}/${key}/${aid}`,b)})
   if(kind==='native-run'){
    payload.checks=rows(['nativeBuild','nativeDesktop','credentialsRestart']);payload.installations=artifacts.map(a=>({artifact:a.name,embedded:{version,sourceCommit,runtimeVersion,architecture,applicationSHA256:sha(Buffer.from(id+' app'))},checks:rows(['cleanInstall','coldStartup','warmStartup'])}))
    const observedRow=contract=>{
     const operation=contract.ipc?contract.operations[0]:'ui-action',before={documentSHA256:sha(Buffer.from('before synthetic'))},after={documentSHA256:sha(Buffer.from('after synthetic'))}
     const actual=contract.ipc?operation==='event'?{trigger:{operation:'synthetic-request'},event:{channel:contract.name,payload:{recordCount:2}},before,after}:{request:{channel:contract.name,transport:operation,arguments:[]},response:{recordCount:2},effects:{before,after}}:{action:{operation,inputs:{fixture:'synthetic-protocol-only'}},before,after}
     return{name:contract.name,status:'passed',source,criterion:contract.criterion,operation,expected:structuredClone(actual),actual,observationId:contract.name,observationAttachment:'semantics.json'}
    }
    payload.functionAssertions=gate.baselineFunctionIds.flatMap(fid=>gate.subassertionsFor(fid,platform)).map(observedRow);payload.ipcAssertions=gate.ipcContracts.map(observedRow)
    let offset=0;const traces=[],observations=[...payload.functionAssertions,...payload.ipcAssertions].map(row=>{const observedAt='2026-10-04T01:00:30Z',raw=Buffer.from(JSON.stringify({subject:row.name,operation:row.operation,observedAt,observation:row.actual})),traceLocator={attachment:'trace.jsonl',byteOffset:offset,byteLength:raw.length,sha256:sha(raw)};traces.push(raw,Buffer.from('\n'));offset+=raw.length+1;return{...row,id:row.observationId,subject:row.name,performed:true,observedAt,traceLocator}})
    attach('trace.jsonl','original-runtime-trace',Buffer.concat(traces));attach('semantics.json','original-semantic-observations',JSON.stringify({schema:1,observationType:'runtime-behavior',source,version,sourceCommit,platformId:id,architecture,runtimeVersion,artifactSHA256,host,run:body.run,observations}))
   }
   if(kind==='screenshots'){payload.captures=['transparent','black-orange','blue-white','custom'].flatMap((theme,t)=>gate.baselineRoutes.map((route,r)=>{const i=t*gate.baselineRoutes.length+r;attach('shot-'+i+'.png','screenshot',images[i%2]);return{attachment:'shot-'+i+'.png',theme,route,state:'normal',zoom:[1,1.25,1.5][i%3],viewport:{width:960,height:620},windowSize:{width:960,height:620}}}))}
   if(kind==='original-video'){const frames=[];payload.recordingAttachment='original.json';payload.interpolated=false;payload.motionROI={x:0,y:0,width:160,height:120};payload.frames=[];for(let i=0;i<40;i++){const file=`frame-${i}.png`,timestamp=i*.025;attach(file,'frame',images[i%2]);frames.push({file,timestamp});payload.frames.push({index:i,attachment:file,timestamp})}attach('original.json','original-frame-manifest',JSON.stringify({version,sourceCommit,platformId:id,architecture,runtimeVersion,artifactSHA256,source:'Page.startScreencast',frames}))}
   if(kind==='frame-timings')Object.assign(payload,{recordingRef:'original-video',fps:39/(39*.025),minimum:30,elapsed:39*.025,frames:40})
   if(kind==='native-game'){Object.assign(payload,{gamePID:1234,launchCommand:'java synthetic unit only',world:{saved:true,fileSHA256:sha(Buffer.from('synthetic world'))},normalExit:{code:0,saved:true},java:{architecture},nativeABI:platform==='harmonyos'?'openharmony-arm64':platform+'-'+architecture});attach('game.png','game-screenshot',images[0]);attach('game.log','game-log','Synthetic unit protocol only')}
   if(kind==='update-rollback'){Object.assign(payload,{checks:rows(['upgrade','bad-payload-rejected','startup-failure-rolls-back','manual-restore']),beforeSHA256:sha(Buffer.from('old')),restoredSHA256:sha(Buffer.from('old'))});attach('update.log','update-log','Synthetic update unit protocol only')}
   if(kind==='function-matrix'){
    const native=bodies.get(id+':native-run').body.payload
    payload.functions=gate.baselineFunctionIds.map(fid=>({id:fid,status:fid==='settings-04'&&platform!=='windows'?'approved-exception':'passed',...(fid==='settings-04'&&platform!=='windows'?{exception:'non-windows-memory-organizer'}:{}),evidenceRefs:['native-run'],assertions:native.functionAssertions.filter(row=>row.name.startsWith(fid+'.')).map(row=>({...row,evidenceRef:'native-run'}))}))
    payload.ipcChannels=native.ipcAssertions.map(row=>({...row,evidenceRef:'native-run'}))
   }
   if(kind==='independent-review')Object.assign(payload,{reviewer:{role:'independent',id:report.independentReviewer},criticalDefects:[],unverifiedRequired:[],scores:{visual:9,interaction:9,motion:9},evidenceRefs:{visual:['screenshots'],interaction:['function-matrix','native-game','update-rollback'],motion:['original-video','frame-timings']}})
   else{payload.nativeReceipt='receipt.json';attach('native.log','native-log','Synthetic unit output only; never native acceptance');attach('receipt.json','native-receipt','{}')}
   const meta={id:key,kind,path:`release/proof/${id}/${key}/proof.json`,sha256:''};entry.evidence.push(meta);bodies.set(id+':'+key,{body,meta});return body
  }
  for(const kind of gate.requiredKinds)add(kind);if(platform==='linux')add('native-run','-ubuntu26','Ubuntu 26.04')
 }
 function rewrite(id,kind,updateReceipt=true){const {body,meta}=bodies.get(id+':'+kind);if(body.kind!=='independent-review'&&updateReceipt){const original=body.attachments.find(a=>a.id===body.payload.nativeReceipt),observed={...body.payload};delete observed.nativeReceipt;const receipt={schema:1,fixture:false,nativeDesktop:true,source:body.source,version:body.version,sourceCommit:body.sourceCommit,platformId:body.platformId,architecture:body.architecture,runtimeVersion:body.runtimeVersion,artifactSHA256:body.artifactSHA256,host:body.host,run:body.run,logAttachment:'native.log',observationsSHA256:sha(Buffer.from(JSON.stringify(observed))),attachments:Object.fromEntries(body.attachments.filter(a=>a.id!==body.payload.nativeReceipt).map(a=>[a.id,{role:a.role,sha256:a.sha256,size:a.size}]))};Object.assign(original,put(root,original.path,JSON.stringify(receipt)))}meta.sha256=put(root,meta.path,JSON.stringify(body)).sha256}
 for(const key of bodies.keys()){const at=key.indexOf(':');rewrite(key.slice(0,at),key.slice(at+1))}
 const save=()=>put(root,`release/${scope==='harmonyos'?'harmonyos':'platform'}-acceptance.json`,JSON.stringify(report));save()
 function rebindSemantic(id,field,name,value){
  const body=bodies.get(id+':native-run').body,row=body.payload[field].find(row=>row.name===name);row.actual=structuredClone(value);row.expected=structuredClone(value)
  const matrix=bodies.get(id+':function-matrix').body,declared=field==='ipcAssertions'?matrix.payload.ipcChannels.find(row=>row.name===name):matrix.payload.functions.flatMap(row=>row.assertions).find(row=>row.name===name);Object.assign(declared,row)
  const attachment=body.attachments.find(row=>row.id==='semantics.json'),doc=JSON.parse(fs.readFileSync(path.join(root,attachment.path))),observed=doc.observations.find(row=>row.subject===name);observed.actual=structuredClone(value);observed.expected=structuredClone(value)
  let offset=0;const traces=[];for(const record of doc.observations){const raw=Buffer.from(JSON.stringify({subject:record.subject,operation:record.operation,observedAt:record.observedAt,observation:record.actual}));record.traceLocator={attachment:'trace.jsonl',byteOffset:offset,byteLength:raw.length,sha256:sha(raw)};traces.push(raw,Buffer.from('\n'));offset+=raw.length+1}
  const trace=body.attachments.find(row=>row.id==='trace.jsonl');Object.assign(trace,put(root,trace.path,Buffer.concat(traces)));Object.assign(attachment,put(root,attachment.path,JSON.stringify(doc)));rewrite(id,'native-run');rewrite(id,'function-matrix');save()
 }
 return{root,report,bodies,save,rewrite,rebindSemantic,body:(id,kind)=>bodies.get(id+':'+kind).body,verify:()=>scope==='harmonyos'?gate.verifyHarmonyRelease(root,version):gate.verifyPlatformRelease(root,version),attachment(id,kind,aid,mutate){const b=this.body(id,kind),a=b.attachments.find(a=>a.id===aid);Object.assign(a,put(root,a.path,mutate(fs.readFileSync(path.join(root,a.path)))));rewrite(id,kind);save()}}
}
function negative(name,change,pattern){test(name,()=>{const f=fixture();change(f);f.save();assert.throws(f.verify,pattern)})}
test('schema-only synthetic positive fixture validates all five desktop targets, including Windows and both Ubuntu versions',()=>{const f=fixture();const accepted=f.verify();assert.deepEqual(accepted.verifiedPlatforms.map(p=>p.id),gate.targets);assert.equal(accepted.verifiedPlatforms.every(p=>p.passed),true)})
test('Harmony gate is separate and requires OpenHarmony Java/LWJGL ABI',()=>{const f=fixture('harmonyos');assert.deepEqual(f.verify().verifiedPlatforms.map(p=>p.id),['harmonyos-arm64']);const body=f.body('harmonyos-arm64','native-game');body.payload.nativeABI='linux-arm64';f.rewrite('harmonyos-arm64','native-game');f.save();assert.throws(f.verify,/游戏ABI不符/)})
negative('legacy boolean and score summary cannot release',f=>{f.report.schema=1},/Expected values/)
negative('current Windows common regression cannot be omitted',f=>{f.report.platforms.shift()},/正式范围/)
negative('Mac/Linux can never stand in for Harmony full completion',f=>{f.report.platforms.push({id:'harmonyos-arm64'})},/正式范围/)
negative('record declared as fixture is rejected even with passing numbers',f=>{f.body('mac-arm64','native-run').source='fixture';f.rewrite('mac-arm64','native-run')},/夹具/)
negative('an original fixture receipt cannot be relabelled native',f=>{const b=f.body('mac-arm64','native-run'),a=b.attachments.find(a=>a.id==='receipt.json'),r=JSON.parse(fs.readFileSync(path.join(f.root,a.path)));r.fixture=true;Object.assign(a,put(f.root,a.path,JSON.stringify(r)));f.rewrite('mac-arm64','native-run',false)},/夹具回执/)
negative('old source identity cannot be relabelled final',f=>{f.body('mac-arm64','native-run').sourceCommit='a'.repeat(40);f.rewrite('mac-arm64','native-run')},/sourceCommit/)
negative('receipt and wrapper must have the same result observations',f=>{f.body('mac-arm64','native-run').payload.checks[0].actual=false;f.rewrite('mac-arm64','native-run',false)},/实际结果/)
negative('wrong runtime or architecture cannot pass',f=>{f.body('mac-arm64','native-run').runtimeVersion='33.4.11';f.rewrite('mac-arm64','native-run')},/runtimeVersion/)
negative('all proof identities must bind final asset hashes',f=>{f.body('mac-arm64','native-run').artifactSHA256={};f.rewrite('mac-arm64','native-run')},/最终附件/)
negative('missing original native receipt cannot pass',f=>{const b=f.body('mac-arm64','native-run');b.attachments=b.attachments.filter(a=>a.id!=='receipt.json');f.rewrite('mac-arm64','native-run',false)},/原始回执/)
negative('false expected native prerequisites cannot be counted passed',f=>{const r=f.body('windows-x64','native-run').payload.checks[0];r.expected=r.actual=false;f.rewrite('windows-x64','native-run')},/必要条件不能预期失败/)
negative('all installed forms must be independently checked',f=>{f.body('windows-x64','native-run').payload.installations.pop();f.rewrite('windows-x64','native-run')},/全部安装形式/)
negative('embedded product identity cannot differ from the final source',f=>{f.body('windows-x64','native-run').payload.installations[0].embedded.sourceCommit='b'.repeat(40);f.rewrite('windows-x64','native-run')},/解包应用身份/)
negative('Linux requires native desktops on both supported Ubuntu versions',f=>{const p=f.report.platforms.find(p=>p.id==='linux-x64');p.evidence=p.evidence.filter(e=>e.id!=='native-run-ubuntu26')},/Ubuntu26.04/)
negative('a text file cannot masquerade as an executable package',f=>{const a=f.report.platforms[0].artifacts[0];Object.assign(a,put(f.root,'release/'+a.name,Buffer.from('not an EXE')))},/附件不是EXE/)
negative('proof and original attachment hashes cannot be stale',f=>{const a=f.body('windows-x64','screenshots').attachments[0];fs.appendFileSync(path.join(f.root,a.path),'tampered')},/大小已变化/)
negative('image extensions cannot turn JSON into screenshots',f=>{f.attachment('windows-x64','screenshots','shot-0.png',()=>Buffer.from('{"status":"passed"}'))},/不是PNG或JPEG/)
negative('all routes and themes remain required',f=>{const p=f.body('windows-x64','screenshots').payload;p.captures=p.captures.map(c=>({...c,route:'home'}));f.rewrite('windows-x64','screenshots')},/页面未覆盖/)
negative('minimum window and scale coverage cannot be skipped',f=>{for(const c of f.body('windows-x64','screenshots').payload.captures)c.windowSize={width:1200,height:800};f.rewrite('windows-x64','screenshots')},/最小窗口/)
negative('old raw frame manifests cannot be relabelled a new source',f=>{f.attachment('windows-x64','original-video','original.json',b=>{const r=JSON.parse(b);r.sourceCommit='c'.repeat(40);return Buffer.from(JSON.stringify(r))})},/原始采集身份/)
negative('raw timestamps cannot be changed in the wrapper',f=>{f.body('windows-x64','original-video').payload.frames[1].timestamp=.026;f.rewrite('windows-x64','original-video')},/原始时间被改写/)
negative('interpolation is not evidence of smooth original capture',f=>{f.body('windows-x64','original-video').payload.interpolated=true;f.rewrite('windows-x64','original-video')},/禁止插帧/)
negative('actual low capture frame rate stays failed',f=>{const p=f.body('windows-x64','original-video').payload;p.frames.forEach((r,i)=>r.timestamp=i*.05);f.attachment('windows-x64','original-video','original.json',b=>{const r=JSON.parse(b);r.frames.forEach((f,i)=>f.timestamp=i*.05);return Buffer.from(JSON.stringify(r))})},/低于固定门槛/)
negative('derived timing statistics cannot replace original measurements',f=>{f.body('windows-x64','frame-timings').payload.fps=60;f.rewrite('windows-x64','frame-timings')},/不能改写帧统计/)
negative('missing applicable functions cannot be counted as full parity',f=>{f.body('windows-x64','function-matrix').payload.functions.pop();f.rewrite('windows-x64','function-matrix')},/功能遗漏/)
negative('a pending function does not pass merely because it has a score',f=>{f.body('windows-x64','function-matrix').payload.functions[0].status='not-tested';f.rewrite('windows-x64','function-matrix')},/功能未通过/)
negative('function rows need actual expected and observed assertions',f=>{f.body('windows-x64','native-run').payload.functionAssertions=[];f.rewrite('windows-x64','native-run')},/实际功能证据逐项语义遗漏/)
negative('OS exception cannot cover unrelated omitted functionality',f=>{f.body('mac-arm64','function-matrix').payload.functions[0]={id:'appearance-01',status:'approved-exception',exception:'non-windows-memory-organizer'};f.rewrite('mac-arm64','function-matrix')},/功能未通过/)
negative('normal Linux ABI cannot establish native Harmony game support',f=>{f.body('linux-arm64','native-game').payload.nativeABI='openharmony-arm64';f.rewrite('linux-arm64','native-game')},/游戏ABI/)
negative('failed rollback cannot be made passed by changing expected result',f=>{const r=f.body('linux-x64','update-rollback').payload.checks[2];r.expected=r.actual=false;f.rewrite('linux-x64','update-rollback')},/必要条件不能预期失败/)
negative('unscored visual acceptance cannot pass',f=>{f.body('windows-x64','independent-review').payload.scores.visual=null;f.rewrite('windows-x64','independent-review')},/评分低于9或未测/)
negative('average nine does not compensate for a single category below nine',f=>{f.body('windows-x64','independent-review').payload.scores={visual:10,interaction:8,motion:9};f.rewrite('windows-x64','independent-review')},/评分低于9或未测/)
negative('score evidence references must exist',f=>{f.body('windows-x64','independent-review').payload.evidenceRefs.visual.push('invented');f.rewrite('windows-x64','independent-review')},/有效证据/)
negative('critical defects cannot coexist with qualified scores',f=>{f.body('windows-x64','independent-review').payload.criticalDefects=['cannot launch'];f.rewrite('windows-x64','independent-review')},/关键缺陷/)
negative('any remaining required coverage is a release blocker',f=>{f.body('windows-x64','independent-review').payload.unverifiedRequired=['actual sound listening'];f.rewrite('windows-x64','independent-review')},/未覆盖/)
negative('evidence path traversal cannot leave the repository',f=>{f.report.platforms[0].evidence[0].path='../receipt.json'},/标准化/)
negative('the inventory cannot be shortened to conceal a missing baseline function',f=>{const file=`docs/validation-${version}/parity-matrix.json`,m=JSON.parse(fs.readFileSync(path.join(f.root,file)));m.features[0].functions.pop();put(f.root,file,JSON.stringify(m))},/完整基线功能库存/)
negative('the inventory cannot remove a page to conceal missing screenshots',f=>{const file=`docs/validation-${version}/parity-matrix.json`,m=JSON.parse(fs.readFileSync(path.join(f.root,file)));m.inventory.routes.pop();put(f.root,file,JSON.stringify(m))},/完整页面库存/)
negative('one page in each theme cannot replace all page and theme combinations',f=>{const p=f.body('windows-x64','screenshots').payload;p.captures=p.captures.filter((c,i)=>i!==p.captures.length-1);f.rewrite('windows-x64','screenshots')},/页面与主题组合/)
negative('fixed280 original IPC inventory cannot be reduced by deleting a matrix row',f=>{const file=`docs/validation-${version}/parity-matrix.json`,m=JSON.parse(fs.readFileSync(path.join(f.root,file)));m.inventory.ipcChannels.pop();m.inventory.ipcChannelCount--;put(f.root,file,JSON.stringify(m))},/280个IPC库存不可缩减/)
negative('an invented channel cannot replace a real baseline channel',f=>{const file=`docs/validation-${version}/parity-matrix.json`,m=JSON.parse(fs.readFileSync(path.join(f.root,file)));m.inventory.ipcChannels[0].channel='invented:fake';put(f.root,file,JSON.stringify(m))},/280个IPC库存不可缩减/)
negative('an acceptance definition cannot be shortened while keeping its functionID',f=>{const file=`docs/validation-${version}/parity-matrix.json`,m=JSON.parse(fs.readFileSync(path.join(f.root,file)));m.features[0].functions[0].acceptance='exists';put(f.root,file,JSON.stringify(m))},/原功能验收定义不能被改写/)
negative('native IPC semantic coverage cannot omit one channel',f=>{f.body('windows-x64','native-run').payload.ipcAssertions.pop();f.rewrite('windows-x64','native-run')},/280接口实际行为逐项语义遗漏/)
negative('function matrix IPC coverage cannot omit one channel',f=>{f.body('windows-x64','function-matrix').payload.ipcChannels.pop();f.rewrite('windows-x64','function-matrix')},/280接口实际行为逐项语义遗漏/)
negative('static existence cannot count as native IPC semantics',f=>{f.body('windows-x64','native-run').payload.ipcAssertions[0].source='static-inventory';f.rewrite('windows-x64','native-run')},/静态存在/)
negative('a whole function boolean cannot replace structured subassertion outcomes',f=>{const row=f.body('windows-x64','native-run').payload.functionAssertions[0];row.expected=row.actual=true;f.rewrite('windows-x64','native-run')},/整行布尔/)
negative('a composite subassertion cannot be omitted from the function row',f=>{f.body('windows-x64','function-matrix').payload.functions[0].assertions.pop();f.rewrite('windows-x64','function-matrix')},/实际功能证据逐项语义遗漏/)
negative('successful wrapper assertions cannot overwrite actual original IPC failures',f=>{const b=f.body('windows-x64','native-run'),a=b.attachments.find(row=>row.id==='semantics.json'),doc=JSON.parse(fs.readFileSync(path.join(f.root,a.path)));doc.observations.find(row=>row.subject==='accounts:list').actual={response:'original failure'};Object.assign(a,put(f.root,a.path,JSON.stringify(doc)));f.rewrite('windows-x64','native-run')},/原始语义结果不能重标/)
negative('expected output does not prove an operation actually ran',f=>{const b=f.body('windows-x64','native-run'),a=b.attachments.find(row=>row.id==='semantics.json'),doc=JSON.parse(fs.readFileSync(path.join(f.root,a.path)));doc.observations[0].performed=false;Object.assign(a,put(f.root,a.path,JSON.stringify(doc)));f.rewrite('windows-x64','native-run')},/未实际执行/)
negative('a passing bool wrapped as an object is not a semantic observation',f=>{const row=f.body('windows-x64','native-run').payload.functionAssertions[0];row.expected=row.actual={passed:true};f.rewrite('windows-x64','native-run')},/操作和可核查前后状态/)
negative('a response declaration cannot replace an IPC result or side effect',f=>{const row=f.body('windows-x64','native-run').payload.ipcAssertions[0];row.expected=row.actual={request:{channel:row.name,transport:row.operation,arguments:[]},response:{passed:true}};f.rewrite('windows-x64','native-run')},/有判定意义/)
negative('an IPC observation cannot pick its own weaker acceptance criterion',f=>{const row=f.body('windows-x64','native-run').payload.ipcAssertions[0];row.criterion='just registered';f.rewrite('windows-x64','native-run')},/判据不能缩减或替换/)
negative('an IPC observation must use its actual fixed transport',f=>{const row=f.body('windows-x64','native-run').payload.ipcAssertions[0];row.operation='event';f.rewrite('windows-x64','native-run')},/操作类型不符合/)
negative('a trace byte range cannot be replaced by a passing semantic aggregate',f=>{const b=f.body('windows-x64','native-run'),a=b.attachments.find(row=>row.id==='semantics.json'),doc=JSON.parse(fs.readFileSync(path.join(f.root,a.path)));delete doc.observations[0].traceLocator;Object.assign(a,put(f.root,a.path,JSON.stringify(doc)));f.rewrite('windows-x64','native-run')},/原trace字节位置/)
negative('semantic actual must match the original runtime trace bytes',f=>{const b=f.body('windows-x64','native-run'),trace=b.attachments.find(row=>row.id==='trace.jsonl'),a=b.attachments.find(row=>row.id==='semantics.json'),doc=JSON.parse(fs.readFileSync(path.join(f.root,a.path))),locator=doc.observations[0].traceLocator,raw=fs.readFileSync(path.join(f.root,trace.path));raw[locator.byteOffset+locator.byteLength-3]=48;Object.assign(trace,put(f.root,trace.path,raw));f.rewrite('windows-x64','native-run')},/原trace片段摘要不符/)
test('synthetic actual bool IPC responses and bool native states keep their original types and trace bytes',()=>{const f=fixture();f.rebindSemantic('windows-x64','ipcAssertions','bridge:installed',{request:{channel:'bridge:installed',transport:'invoke',arguments:[]},response:false});f.rebindSemantic('windows-x64','functionAssertions','appearance-06.09',{action:{operation:'ui-action',inputs:{action:'native-maximize'}},before:{maximized:false},after:{maximized:true}});assert.equal(f.verify().verifiedPlatforms.length,5)})
