<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref} from 'vue'
import {MASCOTS,MascotHoverGate,type MascotState} from '@shared/mascots'
import {useMotion} from '../motion'
import {errText} from '../api'
import {toast} from '../store'
import ConfirmModal from './ConfirmModal.vue'
const emit=defineEmits<{close:[]}>(),{reduced,hidden}=useMotion()
const images=import.meta.glob('../assets/mascots/*.png',{eager:true,import:'default'}) as Record<string,string>
const image=(id:string,layer:string)=>images[`../assets/mascots/${id}-${layer}.png`]
const state=ref<MascotState>({counts:{},order:MASCOTS.map(m=>m.id)}),hit=ref(''),moving=ref(false),reset=ref(false),ready=ref(false),front=ref(true)
const rows=computed(()=>state.value.order.map(id=>MASCOTS.find(m=>m.id===id)!)),gate=new MascotHoverGate()
let timer:ReturnType<typeof setTimeout>|undefined,hitTimer:ReturnType<typeof setTimeout>|undefined,entrance:ReturnType<typeof setTimeout>|undefined,disposed=false
let writes=Promise.resolve()
function move(e:PointerEvent){if(e.pointerType!=='mouse'||front.value||!ready.value||hidden.value||reset.value)return;const target=(e.target as HTMLElement).closest<HTMLElement>('[data-hit]')?.dataset.hit||'';const id=gate.move(e.clientX,e.clientY,target,moving.value);if(id)slap(id)}
function slap(id:string){if(!ready.value||hidden.value||front.value)return;hit.value=id;clearTimeout(hitTimer);hitTimer=setTimeout(()=>hit.value='',600)
  // Serial writes preserve rapid explicit clicks and use the main process's authoritative ordering.
  writes=writes.then(async()=>{try{const next=await window.kamucl.invoke('mascots:slap',id) as MascotState;if(disposed)return;if(next.order.join()!==state.value.order.join()){moving.value=true;clearTimeout(timer);timer=setTimeout(()=>moving.value=false,reduced.value?0:650)}state.value=next}catch(e){if(!disposed)toast(errText(e),'error')}})
}
async function resetCounts(){await writes;try{state.value=await window.kamucl.invoke('mascots:reset',true) as MascotState;reset.value=false;gate.reset()}catch(e){toast(errText(e),'error')}}
onMounted(async()=>{try{state.value=await window.kamucl.invoke('mascots:state') as MascotState;ready.value=true;entrance=setTimeout(()=>front.value=false,reduced.value?0:750)}catch(e){toast(errText(e),'error')}})
onUnmounted(()=>{disposed=true;clearTimeout(timer);clearTimeout(hitTimer);clearTimeout(entrance);gate.reset()})
</script>
<template><Teleport to="body"><div class="modal-mask mascot-mask" @pointerdown.self="emit('close')" @keydown.esc="!reset&&emit('close')"><section class="mascot-stage modal" :class="{reduced,hidden}" role="dialog" aria-modal="true" aria-label="七人互动彩蛋" @pointermove="move" @pointerleave="gate.reset()"><header><div><h2>七人小剧场</h2><p class="muted">移入一次拍一下 · 点击或聚焦后按空格也可互动 · 按累计次数排队</p></div><button class="btn btn-ghost" aria-label="关闭七人互动" @click="emit('close')">×</button></header><div class="stage-floor"><article v-for="mascot in MASCOTS" :key="mascot.id" class="mascot-slot" :class="{hit:hit===mascot.id,walking:moving,front}" :style="{'--position':state.order.indexOf(mascot.id),'--delay':MASCOTS.indexOf(mascot)*-.24+'s'}"><div class="sprite"><img v-if="front" :src="image(mascot.id,'front')" alt=""/><template v-else><img v-for="layer in ['legs','body','head']" :key="layer" :src="image(mascot.id,layer)" :class="'layer-'+layer" alt="" /></template><span v-if="hit===mascot.id" class="feedback" aria-hidden="true">！</span><button class="hit-area" :data-hit="mascot.id" :aria-label="'拍一下 '+mascot.name" :disabled="!ready||front" @click="slap(mascot.id)"></button></div><p class="mascot-label">{{mascot.name}} <b>{{state.counts[mascot.id]||0}}</b></p></article></div><footer><span class="muted" role="status">{{hit?MASCOTS.find(m=>m.id===hit)?.name+'：哎哟！':'完整着装 · 无音效'}}</span><button class="btn btn-ghost btn-sm" @click="reset=true">重置次数</button></footer></section></div><ConfirmModal :open="reset" title="重置互动次数" message="将清空七个人物的累计次数，恢复初始顺序。" confirm-text="确认重置" @cancel="reset=false" @confirm="resetCounts"/></Teleport></template>
<style scoped>
.mascot-mask{align-items:flex-start;padding-top:64px}.mascot-stage{width:min(1020px,calc(100vw - 50px));max-height:calc(100vh - 100px);overflow:auto;padding:24px;transform-origin:0 0;animation:stage-open .5s cubic-bezier(.2,.9,.2,1)}.mascot-stage header,.mascot-stage footer{display:flex;justify-content:space-between;gap:16px;align-items:center}.mascot-stage h2{margin:0;font-size:20px}.mascot-stage header p{font-size:12px;line-height:1.6}.stage-floor{position:relative;height:270px;min-width:560px;border-bottom:1px solid var(--border);background:radial-gradient(ellipse at center bottom,color-mix(in srgb,var(--accent,#ed9f4f) 12%,transparent),transparent 70%)}.mascot-slot{position:absolute;left:0;width:14.2857%;height:260px;transform:translateX(calc(var(--position)*100%));transition:transform .65s cubic-bezier(.4,0,.2,1)}.sprite{position:relative;height:230px;margin:auto;transform-origin:50% 80%;animation:mascot-breathe 3.4s ease-in-out var(--delay) infinite}.sprite img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;pointer-events:none;user-select:none}.hit-area{position:absolute;top:64%;left:30%;width:47%;height:18%;background:transparent;border:0;border-radius:20px;cursor:pointer}.hit-area:focus-visible{outline:2px solid var(--accent,#ed9f4f);outline-offset:4px;background:color-mix(in srgb,var(--accent,#ed9f4f) 15%,transparent)}.mascot-label{text-align:center;font-size:12px;margin:4px 0;white-space:nowrap}.mascot-label b{display:inline-block;min-width:20px;font-variant-numeric:tabular-nums;color:var(--accent,#ed9f4f)}.hit .sprite{animation:mascot-recoil .6s cubic-bezier(.3,.9,.2,1)}.hit .layer-head{animation:head-react .6s ease}.feedback{position:absolute;top:8%;right:8%;font-size:25px;font-weight:800;color:var(--accent,#ed9f4f);animation:feedback .6s ease both}.walking .sprite{animation:mascot-walk .16s ease-in-out infinite alternate}.mascot-stage footer{margin-top:14px;font-size:12px}.hidden *{animation-play-state:paused!important}.reduced,.reduced *{animation:none!important;transition:none!important}@keyframes stage-open{from{opacity:0;transform:scale(.12) translate(-30px,-30px)}to{opacity:1;transform:none}}@keyframes mascot-breathe{50%{transform:translateY(-3px) rotate(.8deg)}}@keyframes mascot-recoil{20%{transform:translateY(6px) scale(1.09,.87) rotate(-3deg)}55%{transform:translateY(-8px) scale(.94,1.05) rotate(2deg)}100%{transform:none}}@keyframes head-react{30%{transform:rotate(-5deg)}70%{transform:rotate(3deg)}}@keyframes mascot-walk{from{transform:translateY(0) rotate(-2deg)}to{transform:translateY(-5px) rotate(2deg)}}@keyframes feedback{from{opacity:0;transform:translateY(8px) scale(.4)}25%{opacity:1;transform:scale(1.2)}to{opacity:0;transform:translateY(-15px)}}@media(max-height:650px){.mascot-mask{padding-top:30px}.stage-floor{height:230px}.mascot-slot{height:215px}.sprite{height:190px}.mascot-stage{max-height:calc(100vh - 60px)}}
</style>
